CREATE TABLE IF NOT EXISTS `gerpro`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `quantity` VARCHAR(255) NULL DEFAULT NULL,
  `price` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci